### ISSUE TITLE
Google chrome grid view extension not working properly. Can't see myself in the window. When you hit grid view the students came up in a straight line down the middle of the computer

### ISSUE THREAD

**Issue by rachelgues** [Fugiman/google-meet-grid-view#211]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by fahhem** [comment]
Duplicate of #202

**Comment by rachelgues** [comment]
How do I fix it then with the new coding?

**Comment by fahhem** [comment]
wait for the new release to get through Chrome team review

**Comment by rachelgues** [comment]
Hope it is soon!!!!!!!!

Sent from my iPhone

On Jun 15, 2020, at 2:43 PM, Fahrzin Hemmati <notifications@github.com> wrote:

﻿

wait for the new release to get through Chrome team review

**Comment by Fugiman** [comment]
(Maybe) fixed in v1.36, please update.

**Comment by rachelgues** [comment]
I updated not fixed    Crashes

Sent from my iPhone

On Jun 16, 2020, at 9:23 PM, Fugi <notifications@github.com> wrote:

﻿

(Maybe) fixed in v1.36, please update.
