### ISSUE TITLE
Grid view only showing 6 participants at most

### ISSUE THREAD

**Issue by greenietea** [Fugiman/google-meet-grid-view#47]

**Comment by ppasler** [comment]
No matter how many people are in the meeting, the grid view only show (in my case) 4 people. This wasn't the case before Easter, so I guess this came with version 2020-4-12.

**Comment by Fugiman** [comment]
Hi, thanks for your report. The latest version (v1.18) should fix this! It was caused by an update by Google modifying the code we hook into.

**Comment by greenietea** [comment]
This doesn't look to be fixed yet. Still experiencing trouble capping at 6 people. @Fugiman

**Comment by greenietea** [comment]
Just saw that it's because Chrome Web Store takes time to review the update.
